version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devicesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    networks:
      - devices-net

  app:
    build: .
    image: devices-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devicesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - devices-net

networks:
  devices-net:
